### ISSUE TITLE
Minor Tweaks

### ISSUE THREAD

**Issue by suicvne** [NaamloosDT/DiscordSharp_Starter#1]
Hi, first I'd like to thank you very much for this starter bot. Makes me happy to see people doing things with my lib and a quick starter bot that isn't filled with scary code like my main bot is is great! I have some minor things I'd like to point out though.
- Personally, I like to setup my events before I call `SendLoginRequest` or `Connect`. Personal preference but there could be a chance that an event isn't hooked up or something.
- I would recommend putting any status updates (Like `UpdateCurrentGame`) inside of the `client.Connected` event to make _sure_ that these functions are only called once connected to ensure they'll go through.
- To prevent any future issues with invite codes, you probably shouldn't hardcode the indexes for join IDs
  - `string inviteID = e.message.Substring(e.message.LastIndexOf('/'), e.message.Length - e.message.LastIndexOf('/)); //or something similar :)`

I will link this repo on my main repo page. Thank you for this again :D

**Comment by Naamloos** [comment]
Thank you for your tips! I'm at school atm but once i get home i'll improve the code :)

**Comment by Naamloos** [comment]
I have updated the project with your tips. Thanks a lot! For both your library and tips :)
