### ISSUE TITLE
Missing nuget packages

### ISSUE THREAD

**Issue by aloisdg** [NaamloosDT/DiscordSharp_Starter#5]
Hello,

When you open the solution, the solution explorer will moaning it cant find a group of nuget package. It can be easily fix by running: `Install-Package DiscordSharp -Pre`, but it is annoying.

Why you didn't add a `packages.config` to the project?

Cheers,

**Comment by Naamloos** [comment]
The Nuget is a bit behind on updates. I always use the latest version of the DiscordSharp repo (the DLL files)

sorry for the late response 
- Naamloos

**Comment by aloisdg** [comment]
> sorry for the late response 

No problem :)
