### ISSUE TITLE
No overload for method 'UpdateCurrentGame' takes 3 arguments

### ISSUE THREAD

**Issue by aloisdg** [NaamloosDT/DiscordSharp_Starter#6]
Hello,

`UpdateCurrentGame()` takes only one argument. I guess DiscordSharp changed.  The single argument is `gameName`. I guess we can replace:

```
client.UpdateCurrentGame("DS_starter!", true, "https://github.com/NaamloosDT/DiscordSharp_Starter");
```

with:

```
client.UpdateCurrentGame("DS_starter!");
```

or even:

```
client.UpdateCurrentGame("DS_starter! => https://github.com/NaamloosDT/DiscordSharp_Starter");
```

What do you think?

**Comment by Naamloos** [comment]
You might know discord changes. So do the API libraries. That line of code is correct. Discord now has a function that lets you connect your twitch acocunt and it will display your stream url.
`client.UpdateCurrentGame(GameName, IsStreaming, StreamURL);`

again, sorry for the late response.
- Naamloos :)

**Comment by aloisdg** [comment]
Thank you!
